export const mockExpenseData = [
  {
    expense: "Housekeeping Supplies",
    category: "Supplies",
    quantity: 10,
    amount: "$500",
    date: "June 1, 2028",
    status: "Completed",
  },
  {
    expense: "Electricity Bill",
    category: "Utilities",
    quantity: 1,
    amount: "$1000",
    date: "June 2, 2028",
    status: "Completed",
  },
  {
    expense: "Marketing Campaign",
    category: "Marketing and Advertising",
    quantity: 1,
    amount: "$2000",
    date: "June 3, 2028",
    status: "Completed",
  },
  {
    expense: "Room Maintenance",
    category: "Maintenance and Repairs",
    quantity: 3,
    amount: "$1200",
    date: "June 4, 2028",
    status: "Completed",
  },
  {
    expense: "Staff Salaries",
    category: "Salaries and Wages",
    quantity: 20,
    amount: "$15000",
    date: "June 5, 2028",
    status: "Completed",
  },
  {
    expense: "Water Bill",
    category: "Utilities",
    quantity: 1,
    amount: "$500",
    date: "June 6, 2028",
    status: "Completed",
  },
  {
    expense: "Event Supplies",
    category: "Supplies",
    quantity: 5,
    amount: "$750",
    date: "June 7, 2028",
    status: "Completed",
  },
  {
    expense: "Plumbing Repair",
    category: "Maintenance and Repairs",
    quantity: 1,
    amount: "$800",
    date: "June 8, 2028",
    status: "Completed",
  },
  {
    expense: "Internet Service",
    category: "Utilities",
    quantity: 1,
    amount: "$300",
    date: "June 9, 2028",
    status: "Completed",
  },
  {
    expense: "Print Advertisements",
    category: "Marketing and Advertising",
    quantity: 1,
    amount: "$500",
    date: "June 10, 2028",
    status: "Completed",
  },
  {
    expense: "Catering Services",
    category: "Supplies",
    quantity: 2,
    amount: "$1500",
    date: "June 11, 2028",
    status: "Completed",
  },
  {
    expense: "Fire Safety Check",
    category: "Maintenance and Repairs",
    quantity: 1,
    amount: "$600",
    date: "June 12, 2028",
    status: "Completed",
  },
  {
    expense: "Water Heater Replacement",
    category: "Utilities",
    quantity: 1,
    amount: "$1300",
    date: "June 13, 2028",
    status: "Completed",
  },
  {
    expense: "Guest Amenities",
    category: "Supplies",
    quantity: 25,
    amount: "$250",
    date: "June 14, 2028",
    status: "Completed",
  },
  {
    expense: "Employee Training",
    category: "Salaries and Wages",
    quantity: 15,
    amount: "$4000",
    date: "June 15, 2028",
    status: "Completed",
  },
  {
    expense: "Parking Lot Maintenance",
    category: "Maintenance and Repairs",
    quantity: 1,
    amount: "$900",
    date: "June 16, 2028",
    status: "Completed",
  },
  {
    expense: "Lighting Bill",
    category: "Utilities",
    quantity: 1,
    amount: "$700",
    date: "June 17, 2028",
    status: "Completed",
  },
  {
    expense: "Outdoor Advertising",
    category: "Marketing and Advertising",
    quantity: 1,
    amount: "$1200",
    date: "June 18, 2028",
    status: "Completed",
  },
  {
    expense: "Website Maintenance",
    category: "Marketing and Advertising",
    quantity: 1,
    amount: "$800",
    date: "June 19, 2028",
    status: "Completed",
  },
  {
    expense: "Garden Maintenance",
    category: "Maintenance and Repairs",
    quantity: 2,
    amount: "$300",
    date: "June 20, 2028",
    status: "Completed",
  },
];
