export const mockHouseKeepingData = [
  {
    roomNumber: "Room 101",
    roomType: "Deluxe",
    housekeeping: "Cleaning in Progress",
    priority: "High",
    floor: "1st",
    reservationStatus: "Checked-In",
    notes: "Guest requested extra towels and pillows.",
  },
  {
    roomNumber: "Room 102",
    roomType: "Standard",
    housekeeping: "Ready",
    priority: "Low",
    floor: "1st",
    reservationStatus: "Reserved",
    notes: "Ensure room is stocked with amenities.",
  },
  {
    roomNumber: "Room 103",
    roomType: "Suite",
    housekeeping: "Needs Cleaning",
    priority: "High",
    floor: "2nd",
    reservationStatus: "Checked-Out",
    notes: "Deep clean due to extended stay.",
  },
  {
    roomNumber: "Room 201",
    roomType: "Standard",
    housekeeping: "Cleaning in Progress",
    priority: "Medium",
    floor: "2nd",
    reservationStatus: "Checked-In",
    notes: "Guest requested fresh linens.",
  },
  {
    roomNumber: "Room 202",
    roomType: "Standard",
    housekeeping: "Needs Cleaning",
    priority: "Medium",
    floor: "2nd",
    reservationStatus: "Checked-Out",
    notes: "Ensure bathroom amenities are replenished.",
  },
  {
    roomNumber: "Room 203",
    roomType: "Deluxe",
    housekeeping: "Ready",
    priority: "Low",
    floor: "2nd",
    reservationStatus: "Reserved",
    notes: "Check minibar supplies and restock if necessary.",
  },
  {
    roomNumber: "Room 204",
    roomType: "Suite",
    housekeeping: "Ready",
    priority: "Medium",
    floor: "3rd",
    reservationStatus: "Checked-In",
    notes: "VIP guest; extra attention required.",
  },
  {
    roomNumber: "Room 205",
    roomType: "Standard",
    housekeeping: "Cleaning in Progress",
    priority: "High",
    floor: "3rd",
    reservationStatus: "Checked-Out",
    notes: "Fresh flowers requested for next guest.",
  },
  {
    roomNumber: "Room 206",
    roomType: "Standard",
    housekeeping: "Needs Cleaning",
    priority: "Medium",
    floor: "3rd",
    reservationStatus: "Checked-In",
    notes: "Guest prefers a quiet room.",
  },
  {
    roomNumber: "Room 207",
    roomType: "Deluxe",
    housekeeping: "Ready",
    priority: "Low",
    floor: "4th",
    reservationStatus: "Reserved",
    notes: "Check view from the window.",
  },
  {
    roomNumber: "Room 208",
    roomType: "Suite",
    housekeeping: "Cleaning in Progress",
    priority: "High",
    floor: "4th",
    reservationStatus: "Checked-In",
    notes: "Celebrate anniversary; special decorations.",
  },
  {
    roomNumber: "Room 209",
    roomType: "Standard",
    housekeeping: "Ready",
    priority: "Medium",
    floor: "4th",
    reservationStatus: "Checked-Out",
    notes: "Guest feedback requested.",
  },
  {
    roomNumber: "Room 210",
    roomType: "Standard",
    housekeeping: "Needs Cleaning",
    priority: "Low",
    floor: "5th",
    reservationStatus: "Checked-In",
    notes: "Extra toiletries requested.",
  },
  {
    roomNumber: "Room 211",
    roomType: "Suite",
    housekeeping: "Ready",
    priority: "High",
    floor: "5th",
    reservationStatus: "Reserved",
    notes: "Guest requires a late checkout.",
  },
  {
    roomNumber: "Room 212",
    roomType: "Deluxe",
    housekeeping: "Cleaning in Progress",
    priority: "Medium",
    floor: "5th",
    reservationStatus: "Checked-Out",
    notes: "Ensure room is well-stocked for next guest.",
  },
  {
    roomNumber: "Room 213",
    roomType: "Standard",
    housekeeping: "Ready",
    priority: "Low",
    floor: "6th",
    reservationStatus: "Checked-In",
    notes: "Guest enjoys the view; avoid blocking.",
  },
  {
    roomNumber: "Room 214",
    roomType: "Standard",
    housekeeping: "Needs Cleaning",
    priority: "Medium",
    floor: "6th",
    reservationStatus: "Checked-Out",
    notes: "Inspect room for damages.",
  },
  {
    roomNumber: "Room 215",
    roomType: "Suite",
    housekeeping: "Ready",
    priority: "High",
    floor: "6th",
    reservationStatus: "Reserved",
    notes: "Complimentary champagne for the guests.",
  },
  {
    roomNumber: "Room 216",
    roomType: "Deluxe",
    housekeeping: "Cleaning in Progress",
    priority: "Medium",
    floor: "7th",
    reservationStatus: "Checked-In",
    notes: "Guest is allergic to certain scents.",
  },
  {
    roomNumber: "Room 217",
    roomType: "Standard",
    housekeeping: "Ready",
    priority: "Low",
    floor: "7th",
    reservationStatus: "Checked-Out",
    notes: "Follow up on guest's stay.",
  },
  {
    roomNumber: "Room 218",
    roomType: "Suite",
    housekeeping: "Needs Cleaning",
    priority: "High",
    floor: "7th",
    reservationStatus: "Checked-In",
    notes: "Special arrangements for children.",
  },
  {
    roomNumber: "Room 219",
    roomType: "Standard",
    housekeeping: "Ready",
    priority: "Medium",
    floor: "8th",
    reservationStatus: "Reserved",
    notes: "Guest has a pet; ensure pet amenities are available.",
  },
  {
    roomNumber: "Room 220",
    roomType: "Deluxe",
    housekeeping: "Cleaning in Progress",
    priority: "Low",
    floor: "8th",
    reservationStatus: "Checked-Out",
    notes: "Check for any lost items.",
  },
  {
    roomNumber: "Room 221",
    roomType: "Suite",
    housekeeping: "Ready",
    priority: "High",
    floor: "9th",
    reservationStatus: "Checked-In",
    notes: "Extra coffee and snacks requested.",
  },
  {
    roomNumber: "Room 222",
    roomType: "Standard",
    housekeeping: "Needs Cleaning",
    priority: "Medium",
    floor: "9th",
    reservationStatus: "Checked-Out",
    notes: "Room requires maintenance check.",
  },
  {
    roomNumber: "Room 223",
    roomType: "Deluxe",
    housekeeping: "Ready",
    priority: "Low",
    floor: "10th",
    reservationStatus: "Reserved",
    notes: "Guest prefers quiet floor.",
  },
  {
    roomNumber: "Room 224",
    roomType: "Suite",
    housekeeping: "Cleaning in Progress",
    priority: "High",
    floor: "10th",
    reservationStatus: "Checked-In",
    notes: "Guest is celebrating a birthday.",
  },
  {
    roomNumber: "Room 225",
    roomType: "Standard",
    housekeeping: "Ready",
    priority: "Medium",
    floor: "10th",
    reservationStatus: "Checked-Out",
    notes: "Room needs extra cleaning before next guest.",
  },
  {
    roomNumber: "Room 226",
    roomType: "Standard",
    housekeeping: "Needs Cleaning",
    priority: "Low",
    floor: "11th",
    reservationStatus: "Checked-In",
    notes: "Inspect for room damage.",
  },
  {
    roomNumber: "Room 227",
    roomType: "Suite",
    housekeeping: "Ready",
    priority: "High",
    floor: "11th",
    reservationStatus: "Reserved",
    notes: "Ensure all amenities are stocked.",
  },
  {
    roomNumber: "Room 228",
    roomType: "Deluxe",
    housekeeping: "Cleaning in Progress",
    priority: "Medium",
    floor: "11th",
    reservationStatus: "Checked-Out",
    notes: "Check if guest left any belongings.",
  },
  {
    roomNumber: "Room 229",
    roomType: "Standard",
    housekeeping: "Ready",
    priority: "Low",
    floor: "12th",
    reservationStatus: "Checked-In",
    notes: "Confirm late checkout request.",
  },
  {
    roomNumber: "Room 230",
    roomType: "Standard",
    housekeeping: "Needs Cleaning",
    priority: "Medium",
    floor: "12th",
    reservationStatus: "Checked-Out",
    notes: "Inspect for lost items.",
  },
];
