import { faker } from "@faker-js/faker";

export const mockInventoryData = [
  {
    itemName: "Bath Towels",
    category: "Linen",
    availability: "Available",
    quantityInStock: 120,
    quantityInReorder: 50,
    imageUrl: faker.image.url({
      width: 50,
      height: 50,
      category: "nature",
    }),
  },
  {
    itemName: "Shampoo Bottles",
    category: "Toiletries",
    availability: "Low",
    quantityInStock: 20,
    quantityInReorder: 100,
    imageUrl: faker.image.url({
      width: 50,
      height: 50,
      category: "nature",
    }),
  },
  {
    itemName: "Coffee Pods",
    category: "Refreshments",
    availability: "Out of Stock",
    quantityInStock: 0,
    quantityInReorder: 200,
    imageUrl: faker.image.url({
      width: 50,
      height: 50,
      category: "nature",
    }),
  },
  {
    itemName: "Room Key Cards",
    category: "Electronics",
    availability: "Available",
    quantityInStock: 500,
    quantityInReorder: 100,
    imageUrl: faker.image.url({
      width: 50,
      height: 50,
      category: "nature",
    }),
  },
  {
    itemName: "Cleaning Supplies",
    category: "Housekeeping",
    availability: "Available",
    quantityInStock: 300,
    quantityInReorder: 50,
    imageUrl: faker.image.url({
      width: 50,
      height: 50,
      category: "nature",
    }),
  },
  {
    itemName: "Mini Bar Snacks",
    category: "Refreshments",
    availability: "Low",
    quantityInStock: 15,
    quantityInReorder: 50,
    imageUrl: faker.image.url({
      width: 50,
      height: 50,
      category: "nature",
    }),
  },
  {
    itemName: "Bed Linens",
    category: "Linen",
    availability: "Available",
    quantityInStock: 80,
    quantityInReorder: 30,
    imageUrl: faker.image.url({
      width: 50,
      height: 50,
      category: "nature",
    }),
  },
  {
    itemName: "Bathrobes",
    category: "Linen",
    availability: "Low",
    quantityInStock: 10,
    quantityInReorder: 50,
    imageUrl: faker.image.url({
      width: 50,
      height: 50,
      category: "nature",
    }),
  },
  {
    itemName: "Slippers",
    category: "Guest Comfort",
    availability: "Available",
    quantityInStock: 150,
    quantityInReorder: 50,
    imageUrl: faker.image.url({
      width: 50,
      height: 50,
      category: "nature",
    }),
  },
  {
    itemName: "Water Bottles",
    category: "Refreshments",
    availability: "Available",
    quantityInStock: 200,
    quantityInReorder: 100,
    imageUrl: faker.image.url({
      width: 50,
      height: 50,
      category: "nature",
    }),
  },
  {
    itemName: "Kettle",
    category: "Kitchen",
    availability: "Out of Stock",
    quantityInStock: 0,
    quantityInReorder: 130,
    imageUrl: faker.image.url({
      width: 50,
      height: 50,
      category: "nature",
    }),
  },
  {
    itemName: "Bath Mats",
    category: "Linen",
    availability: "Available",
    quantityInStock: 75,
    quantityInReorder: 30,
    imageUrl: faker.image.url({
      width: 50,
      height: 50,
      category: "nature",
    }),
  },
  {
    itemName: "Toothpaste",
    category: "Toiletries",
    availability: "Low",
    quantityInStock: 25,
    quantityInReorder: 100,
    imageUrl: faker.image.url({
      width: 50,
      height: 50,
      category: "nature",
    }),
  },
  {
    itemName: "Room Fragrance",
    category: "Guest Comfort",
    availability: "Available",
    quantityInStock: 50,
    quantityInReorder: 20,
    imageUrl: faker.image.url({
      width: 50,
      height: 50,
      category: "nature",
    }),
  },
  {
    itemName: "Ironing Boards",
    category: "Housekeeping",
    availability: "Available",
    quantityInStock: 40,
    quantityInReorder: 15,
    imageUrl: faker.image.url({
      width: 50,
      height: 50,
      category: "nature",
    }),
  },
  {
    itemName: "Pillows",
    category: "Linen",
    availability: "Available",
    quantityInStock: 60,
    quantityInReorder: 20,
    imageUrl: faker.image.url({
      width: 50,
      height: 50,
      category: "nature",
    }),
  },
  {
    itemName: "Hair Dryers",
    category: "Electronics",
    availability: "Low",
    quantityInStock: 12,
    quantityInReorder: 30,
    imageUrl: faker.image.url({
      width: 50,
      height: 50,
      category: "nature",
    }),
  },
  {
    itemName: "Soap Bars",
    category: "Toiletries",
    availability: "Available",
    quantityInStock: 250,
    quantityInReorder: 75,
    imageUrl: faker.image.url({
      width: 50,
      height: 50,
      category: "nature",
    }),
  },
  {
    itemName: "Mugs",
    category: "Kitchen",
    availability: "Available",
    quantityInStock: 180,
    quantityInReorder: 60,
    imageUrl: faker.image.url({
      width: 50,
      height: 50,
      category: "nature",
    }),
  },
  {
    itemName: "Trash Bags",
    category: "Housekeeping",
    availability: "Out of Stock",
    quantityInStock: 0,
    quantityInReorder: 150,
    imageUrl: faker.image.url({
      width: 50,
      height: 50,
      category: "nature",
    }),
  },
];
