// mockData.js

export const mockInvoiceData = [
  {
    guest: "Angus Copper",
    bookingId: "LG-800108",
    room: "Deluxe 101",
    price: "$150",
    duration: "3 nights",
    amount: "$450",
    status: "Paid",
  },
  {
    guest: "Catherine Lopp",
    bookingId: "LG-800109",
    room: "Standard 202",
    price: "$100",
    duration: "2 nights",
    amount: "$200",
    status: "Unpaid",
  },
  {
    guest: "Edgar Irving",
    bookingId: "LG-800110",
    room: "Suite 303",
    price: "$250",
    duration: "5 nights",
    amount: "$1250",
    status: "Paid",
  },
  {
    guest: "Gertrude Bale",
    bookingId: "LG-800111",
    room: "Standard 204",
    price: "$100",
    duration: "1 night",
    amount: "$100",
    status: "Unpaid",
  },
  {
    guest: "Ice B. Holand",
    bookingId: "LG-800112",
    room: "Deluxe 105",
    price: "$150",
    duration: "5 nights",
    amount: "$750",
    status: "Paid",
  },
  {
    guest: "Sarah Johnson",
    bookingId: "LG-800113",
    room: "Standard 305",
    price: "$100",
    duration: "2 nights",
    amount: "$200",
    status: "Paid",
  },
  {
    guest: "Kevin Lee",
    bookingId: "LG-800114",
    room: "Suite 306",
    price: "$250",
    duration: "3 nights",
    amount: "$750",
    status: "Unpaid",
  },
  {
    guest: "Laura Martin",
    bookingId: "LG-800115",
    room: "Deluxe 107",
    price: "$150",
    duration: "1 night",
    amount: "$150",
    status: "Paid",
  },
  {
    guest: "Robert Kling",
    bookingId: "LG-800116",
    room: "Standard 208",
    price: "$100",
    duration: "2 nights",
    amount: "$200",
    status: "Unpaid",
  },
  {
    guest: "Olivia White",
    bookingId: "LG-800117",
    room: "Suite 310",
    price: "$250",
    duration: "5 nights",
    amount: "$1250",
    status: "Paid",
  },
  {
    guest: "Catherine Lopp",
    bookingId: "LG-800118",
    room: "Deluxe 110",
    price: "$150",
    duration: "1 night",
    amount: "$150",
    status: "Paid",
  },
  {
    guest: "Catherine Lopp",
    bookingId: "LG-800119",
    room: "Standard 307",
    price: "$100",
    duration: "3 nights",
    amount: "$300",
    status: "Unpaid",
  },
  {
    guest: "Jason Green",
    bookingId: "LG-800120",
    room: "Suite 102",
    price: "$300",
    duration: "5 nights",
    amount: "$1500",
    status: "Paid",
  },
  {
    guest: "Sophia Brown",
    bookingId: "LG-800121",
    room: "Standard 306",
    price: "$120",
    duration: "2 nights",
    amount: "$240",
    status: "Unpaid",
  },
  {
    guest: "Liam Scott",
    bookingId: "LG-800122",
    room: "Suite 401",
    price: "$200",
    duration: "4 nights",
    amount: "$800",
    status: "Paid",
  },
  {
    guest: "Emma Lee",
    bookingId: "LG-800123",
    room: "Deluxe 108",
    price: "$180",
    duration: "3 nights",
    amount: "$540",
    status: "Paid",
  },
  {
    guest: "Oliver King",
    bookingId: "LG-800124",
    room: "Standard 210",
    price: "$100",
    duration: "2 nights",
    amount: "$200",
    status: "Unpaid",
  },
  {
    guest: "Amelia Ford",
    bookingId: "LG-800125",
    room: "Deluxe 109",
    price: "$160",
    duration: "4 nights",
    amount: "$640",
    status: "Paid",
  },
  {
    guest: "James Clarke",
    bookingId: "LG-800126",
    room: "Suite 204",
    price: "$220",
    duration: "5 nights",
    amount: "$1100",
    status: "Unpaid",
  },
  {
    guest: "Mia White",
    bookingId: "LG-800127",
    room: "Standard 302",
    price: "$130",
    duration: "3 nights",
    amount: "$390",
    status: "Paid",
  },
];
